language: php

sudo: required

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.4.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: nightly

before_script:
  - pecl -q install xhprof-beta && echo "extension=xhprof.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "5.5" && "$SYMFONY_VERSION" == "" ]]; then composer require "symfony/asset" --no-update; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" && "$SYMFONY_VERSION" == "" ]]; then composer require "symfony/asset" --no-update; fi;
  - if [[ "$TRAVIS_PHP_VERSION" = 7.* && "$SYMFONY_VERSION" == "" ]]; then composer require "symfony/asset" "symfony/yaml" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: ./vendor/bin/phpunit
